name: docker

on:
  push:
    branches:
    - main
    - stable
    - unstable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_BUILD_SUMMARY: true
  REPO_NAME: $GITHUB_REPOSITORY

jobs:
    build-docker-single-arch:
        name: build-docker-${{ matrix.cpu_arch }}
        runs-on: ubuntu-22.04
        strategy:
          fail-fast: false
          # matrix:
          #   cpu_arch: [aarch64, x86_64]
        steps:

          - uses: actions/checkout@v4
          - name: Update Rust
            run: rustup update stable
          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
              username: ${{ env.DOCKER_USERNAME }}
              password: ${{ env.DOCKER_PASSWORD }}
              
          - name: Cross build binaries
            run: |
                cargo install cross
                make build-${{ matrix.cpu_arch }}
            timeout-minutes: 100

          

       



          - name: Install QEMU
            run: sudo apt-get update && sudo apt-get install -y qemu-user-static

          - name: Build using Make
            run: make build

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push using Bake
            uses: docker/bake-action@v6
            with:
              files: ./docker-bake.hcl
              source: .
              push: true
              load: true # <--- Ensure the image is loaded into the local Docker daemon
              set: |
                *.context=.
                *.tags=${{ github.repository }}:${{ github.ref_name }}
            env:
              ARCH: ${{ env.SHORT_ARCH }}
              GITHUB_REPO: ${{ github.repository }}
              DOCKER_BUILD_RECORD_UPLOAD: true
